spring:
  application:
    name: spring-gift

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test

  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true

  config:
    import: application-secret.yml


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
