kakao :
  login :
    REST-API-KEY :
      892fe1d70b47ecc4ea2afb2a9cb98c25
    REDIRECT-URI :
      http://localhost:8080/api/members/kakao-login/callback
jwt:
  secret: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
  expiration: 86400